"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";

type Item = { id: string; quantity: number; product: { name: string; price_cents: number } | null };
type Vehicle = { id: string; make: string; model: string; model_year: number };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
export default function CartPage() {
  const [cartId, setCartId] = useState(""); const [items, setItems] = useState<Item[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [vehicleId, setVehicleId] = useState(""); const [locationText, setLocationText] = useState(""); const [notes, setNotes] = useState(""); const [message, setMessage] = useState(""); const [checkingOut, setCheckingOut] = useState(false);
  async function load() { if (!isSupabaseConfigured) return; const db = createBrowserSupabaseClient(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return setMessage("Sign in from services & upgrades to use a cart."); const { data: cart } = await db.from("carts").select("id,cart_items(id,quantity,product:catalog_products(name,price_cents))").eq("user_id", auth.user.id).eq("status", "active").maybeSingle(); setCartId(cart?.id ?? ""); setItems((cart?.cart_items ?? []).map((item) => ({ ...item, product: Array.isArray(item.product) ? item.product[0] ?? null : item.product })) as unknown as Item[]); const { data: vehicleRows } = await db.from("vehicle_catalog").select("id,make,model,model_year").not("powertrain", "is", null).order("make").limit(500); setVehicles((vehicleRows ?? []) as Vehicle[]); }
  useEffect(() => { void load(); }, []);
  async function remove(id: string) { const { error } = await createBrowserSupabaseClient().from("cart_items").delete().eq("id", id); if (error) setMessage(error.message); else { window.dispatchEvent(new Event("volt-yard-cart-updated")); void load(); } }
  async function checkout() { if (checkingOut || !cartId || !items.length) return; setCheckingOut(true); setMessage(""); try { const db = createBrowserSupabaseClient(); const { data: session } = await db.auth.getSession(); if (!session.session) { setMessage("Sign in before checkout."); return; } const response = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${session.session.access_token}`, "idempotency-key": crypto.randomUUID() }, body: JSON.stringify({ cartId, vehicleId: vehicleId || null, locationText, notes }) }); const data: { url?: string; error?: string } = await response.json().catch(() => ({})); if (data.url) { window.location.assign(data.url); return; } setMessage(data.error ?? "Could not begin checkout."); } catch { setMessage("Could not begin checkout. Please try again."); } finally { setCheckingOut(false); } }
  const total = items.reduce((sum, item) => sum + item.quantity * (item.product?.price_cents ?? 0), 0);
  return <main className="commerce wrap"><header className="commerce-head"><p className="eyebrow">Your cart</p><h1>Set up service.</h1><p>Payment is completed only on Stripe Checkout. We send paid service requests to compatible installers.</p></header>{message && <p className="form-message">{message}</p>}<section className="cart-layout"><div className="cart-items">{items.map((item) => <div className="cart-item" key={item.id}><div><strong>{item.product?.name}</strong><p>Quantity {item.quantity}</p></div><div><strong>{money((item.product?.price_cents ?? 0) * item.quantity)}</strong><button onClick={() => remove(item.id)}>Remove</button></div></div>)}{!items.length && <p>Your cart is empty. <Link href="/catalog">Browse services & upgrades.</Link></p>}</div><aside className="checkout-card"><label>Vehicle (optional)<select value={vehicleId} onChange={(event) => setVehicleId(event.target.value)}><option value="">Choose later</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.model_year} {vehicle.make} {vehicle.model}</option>)}</select></label><label>City, state, or ZIP<input value={locationText} onChange={(event) => setLocationText(event.target.value)} placeholder="Used to guide installers" /></label><label>Request notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Access, timing, or vehicle details" /></label><p className="cart-total">Total <strong>{money(total)}</strong></p><button disabled={checkingOut || !items.length} onClick={checkout}>{checkingOut ? "Opening Stripe..." : "Continue to Stripe Checkout"}</button></aside></section></main>;
}
