"use client";
import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import { AdminNavigation } from "@/app/portal-navigation";
type Profile = { id: string; full_name: string | null; membership_tier: "free" | "member" | "premium" };
type Payout = { id: string; amount_cents: number; expert_id: string };
export default function MembershipAdminPage() {
  const router = useRouter(); const [profiles, setProfiles] = useState<Profile[]>([]); const [payouts, setPayouts] = useState<Payout[]>([]); const [message, setMessage] = useState("");
  const load = useCallback(async () => { if (!isSupabaseConfigured) return; const db = createBrowserSupabaseClient(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return router.replace("/"); const { data: me } = await db.from("profiles").select("is_admin").eq("id", auth.user.id).maybeSingle(); if (!me?.is_admin) return router.replace("/portal"); const [people, jobs] = await Promise.all([db.from("profiles").select("id,full_name,membership_tier").order("created_at", { ascending: false }).limit(100), db.from("expert_payout_jobs").select("id,amount_cents,expert_id").eq("status", "pending")]); setProfiles((people.data ?? []) as Profile[]); setPayouts((jobs.data ?? []) as Payout[]); }, [router]); useEffect(() => { void load(); }, [load]);
  async function setTier(id: string, tier: Profile["membership_tier"]) { const db = createBrowserSupabaseClient(); const { error } = await db.from("profiles").update({ membership_tier: tier }).eq("id", id); if (!error && tier !== "free") await db.from("membership_subscriptions").upsert({ user_id: id, tier, status: "active", source: "admin_demo" }, { onConflict: "user_id" }); setMessage(error?.message || "Membership updated."); void load(); }
  async function pay(id: string) { const { error } = await createBrowserSupabaseClient().from("expert_payout_jobs").update({ status: "paid", paid_at: new Date().toISOString(), payout_reference: "admin-recorded" }).eq("id", id); setMessage(error?.message || "Payout recorded."); void load(); }
  return <main className="portal"><section className="portal-head"><p className="eyebrow">Admin management</p><h1>Memberships and expert payouts.</h1><p>Demo tiers are an internal override. Stripe webhooks remain the source for Stripe subscriptions.</p></section><AdminNavigation /><p className="form-message">{message}</p><section className="admin-list">{profiles.map((profile) => <article className="admin-shop" key={profile.id}><h2>{profile.full_name || profile.id}</h2><label>Tier<select value={profile.membership_tier} onChange={(event) => setTier(profile.id, event.target.value as Profile["membership_tier"])}><option value="free">Free</option><option value="member">Member</option><option value="premium">Premium</option></select></label></article>)}</section><section className="admin-list">{payouts.map((job) => <article className="admin-shop" key={job.id}><p>Expert {job.expert_id}</p><h2>${(job.amount_cents / 100).toFixed(2)}</h2><button onClick={() => pay(job.id)}>Record manual payout</button></article>)}</section></main>;
}
