"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import { defaultLocale, localeFromPath } from "@/lib/i18n";
import { useLocalizedContent } from "@/lib/localized-content";

type Category = { id: string; name: string; slug: string; description: string | null };
type Topic = { id: string; slug: string; title: string; body: string; score: number; is_pinned: boolean; created_at: string; community_categories: Category | null };
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export default function CommunityPage() {
  const locale = typeof window === "undefined" ? defaultLocale : localeFromPath(window.location.pathname);
  const t = useLocalizedContent(locale);
  const [topics, setTopics] = useState<Topic[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [status, setStatus] = useState("Loading conversations..."); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [categoryId, setCategoryId] = useState(""); const [filter, setFilter] = useState(""); const [showForm, setShowForm] = useState(false);
  const load = async () => { if (!isSupabaseConfigured) return setStatus("Community is not configured."); const db = createBrowserSupabaseClient(); const [categoryResult, topicResult] = await Promise.all([db.from("community_categories").select("id,name,slug,description").eq("active", true).order("sort_order").order("name"), db.from("community_topics").select("id,slug,title,body,score,is_pinned,created_at,community_categories(id,name,slug,description)").in("moderation_state", ["published", "locked"]).order("is_pinned", { ascending: false }).order("score", { ascending: false }).order("last_activity_at", { ascending: false })]); if (categoryResult.error || topicResult.error) return setStatus((categoryResult.error || topicResult.error)?.message ?? "Conversations could not be loaded."); const loadedCategories = (categoryResult.data ?? []) as Category[]; setCategories(loadedCategories); setCategoryId((value) => value || loadedCategories[0]?.id || ""); setTopics((topicResult.data ?? []) as unknown as Topic[]); setStatus(""); };
  useEffect(() => { void load(); }, []);
  async function publish(event: FormEvent) { event.preventDefault(); if (!isSupabaseConfigured) return; const db = createBrowserSupabaseClient(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return setStatus("Sign in to ask the community."); if (!categoryId) return setStatus("Choose a category."); const { error } = await db.from("community_topics").insert({ author_id: auth.user.id, title: title.trim(), body: body.trim(), category_id: categoryId, slug: `${slugify(title)}-${Date.now().toString(36)}`, moderation_state: "pending" }); if (error) return setStatus(error.message); setTitle(""); setBody(""); setShowForm(false); setStatus("Question submitted for moderator review."); }
  const visibleTopics = filter ? topics.filter((topic) => topic.community_categories?.id === filter) : topics;
  return <main className="content-page wrap"><header className="content-head community-head"><div><p className="eyebrow">Volt Yard community</p><h1>Ask owners who have been there.</h1><p>Compare notes, learn what is normal, and know when it is time to bring in a specialist.</p></div><button className="inline-cta" onClick={() => setShowForm((value) => !value)}>Ask the community</button></header>{showForm && <form className="community-form" onSubmit={publish}><label>Question title<input required minLength={8} maxLength={180} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="What are you trying to solve?" /></label><label>Category<select required value={categoryId} onChange={(event) => setCategoryId(event.target.value)}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Details<textarea required minLength={20} maxLength={10000} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Include your vehicle, symptoms, and what you have already checked." /></label><button type="submit">Submit question</button></form>}<div className="community-toolbar"><label>Filter topics<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><span>Trending now</span></div><p className="directory-status">{status}</p><section className="topic-list">{visibleTopics.map((topic) => <article className="topic-card" key={topic.id}><p className="eyebrow">{topic.is_pinned ? "Pinned · " : ""}{topic.community_categories?.name} · {new Date(topic.created_at).toLocaleDateString()}</p><h2><Link href={`/community/${topic.slug}`}>{topic.title}</Link></h2><p>{topic.body}</p><div className="topic-card-footer"><span className="score">{topic.score >= 0 ? "+" : ""}{topic.score} score</span><Link href={`/community/${topic.slug}`}>Join conversation →</Link></div></article>)}</section>{!status && !visibleTopics.length && <p className="empty-copy">No published topics in this category yet.</p>}</main>;
}
