"use client";

import Link from "@/app/locale-link";
import { useEffect, useState } from "react";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import { Button, PageHeader } from "@/app/page-primitives";

type Job = { id: string; status: string; installer_payout_cents: number; payout_status: string; service_request: { location_text: string | null; notes: string | null; product: { name: string } | null; vehicle: { make: string; model: string; model_year: number } | null } | null };
const money = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);

export default function InstallerWorkPage() {
  const [jobs, setJobs] = useState<Job[]>([]); const [message, setMessage] = useState(""); const [agreement, setAgreement] = useState<Record<string, boolean>>({});
  async function load() { if (!isSupabaseConfigured) return; const db = createBrowserSupabaseClient(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return setMessage("Sign in through the partner portal to view your work queue."); const { data: shop } = await db.from("shops").select("id").eq("owner_id", auth.user.id).maybeSingle(); if (!shop) return setMessage("Create and publish your partner profile first."); const { data, error } = await db.from("installer_jobs").select("id,status,installer_payout_cents,payout_status,service_request:service_requests(location_text,notes,product:catalog_products(name),vehicle:vehicle_catalog(make,model,model_year))").eq("shop_id", shop.id).in("status", ["open", "accepted"]).order("created_at", { ascending: false }); if (error) setMessage(error.message); else setJobs((data ?? []) as unknown as Job[]); }
  useEffect(() => { void load(); }, []);
  async function accept(jobId: string) { if (!agreement[jobId]) return setMessage("Accept the managed service agreement before claiming work."); const { data, error } = await createBrowserSupabaseClient().rpc("accept_installer_job", { job_id: jobId, agreement_version: "2026-10-02-managed-service" }); if (error) setMessage(error.message); else if (!data) setMessage("This request was already claimed."); else setMessage("Request claimed. Your agreed payout obligation is now recorded."); void load(); }
  return <main className="commerce wrap"><PageHeader className="commerce-head" eyebrow="Partner work queue" title="Requests matched to your capabilities." intro="Volt Yard manages the customer service and offers compatible partners a pre-negotiated payout for fulfillment." />{message && <p className="form-message">{message}</p>}<section className="job-list">{jobs.map((job) => <article className="job-card" key={job.id}><p className="eyebrow">{job.status}</p><h2>{job.service_request?.product?.name ?? "Service request"}</h2><p>{job.service_request?.vehicle ? `${job.service_request.vehicle.model_year} ${job.service_request.vehicle.make} ${job.service_request.vehicle.model}` : "Vehicle to be confirmed"}</p>{job.service_request?.location_text && <p>Location: {job.service_request.location_text}</p>}{job.service_request?.notes && <p>Notes: {job.service_request.notes}</p>}<p className="fee">Agreed fulfillment payout: {money(job.installer_payout_cents)}</p>{job.status === "open" ? <><label className="agreement"><input type="checkbox" checked={agreement[job.id] ?? false} onChange={(event) => setAgreement({ ...agreement, [job.id]: event.target.checked })} /> I accept the Volt Yard managed service agreement and the stated payout (version 2026-10-02-managed-service).</label><Button onClick={() => accept(job.id)}>Accept request</Button></> : <strong>Claimed by your business. Payout status: {job.payout_status}.</strong>}</article>)}{!jobs.length && !message && <p>No open requests are assigned to your business right now.</p>}</section></main>;
}
