"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
type Category = { name: string };
type Topic = { id: string; title: string; body: string; score: number; moderation_state: string; created_at: string; community_categories: Category | null };
type Post = { id: string; body: string; score: number; created_at: string };

export default function TopicPage({ params }: { params: Promise<{ slug: string }> }) {
  const [topic, setTopic] = useState<Topic | null>(null); const [posts, setPosts] = useState<Post[]>([]); const [votes, setVotes] = useState<Record<string, number>>({}); const [topicVote, setTopicVote] = useState<number | null>(null); const [body, setBody] = useState(""); const [status, setStatus] = useState("Loading conversation...");
  const load = async (slug: string) => { if (!isSupabaseConfigured) return setStatus("Community is not configured."); const db = createBrowserSupabaseClient(); const { data, error } = await db.from("community_topics").select("id,title,body,score,moderation_state,created_at,community_categories(name)").eq("slug", slug).in("moderation_state", ["published", "locked"]).maybeSingle(); if (error || !data) return setStatus("This topic is unavailable."); setTopic(data as unknown as Topic); const [postResult, authResult] = await Promise.all([db.from("community_posts").select("id,body,score,created_at").eq("topic_id", data.id).eq("moderation_state", "published").order("score", { ascending: false }).order("created_at"), db.auth.getUser()]); setPosts((postResult.data ?? []) as Post[]); if (postResult.error) setStatus("Replies could not be loaded."); else setStatus(""); if (authResult.data.user) { const [topicVoteResult, postVoteResult] = await Promise.all([db.from("community_topic_votes").select("value").eq("topic_id", data.id).eq("user_id", authResult.data.user.id).maybeSingle(), db.from("community_post_votes").select("post_id,value").eq("user_id", authResult.data.user.id).in("post_id", (postResult.data ?? []).map((post) => post.id))]); setTopicVote(topicVoteResult.data?.value ?? null); setVotes(Object.fromEntries((postVoteResult.data ?? []).map((vote) => [vote.post_id, vote.value]))); } };
  useEffect(() => { void params.then(({ slug }) => load(slug)); }, [params]);
  async function vote(kind: "topic" | "post", id: string, value: number) { if (!isSupabaseConfigured) return; const db = createBrowserSupabaseClient(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return setStatus("Sign in with a Member or Premium account to vote."); const current = kind === "topic" ? topicVote : votes[id] ?? null; const { error } = await db.rpc("community_set_vote", { target_kind: kind, target_id: id, vote_value: current === value ? null : value }); if (error) return setStatus(error.message); void params.then(({ slug }) => load(slug)); }
  async function reply(event: FormEvent) { event.preventDefault(); if (!topic || !isSupabaseConfigured) return; const db = createBrowserSupabaseClient(); const { data: auth } = await db.auth.getUser(); if (!auth.user) return setStatus("Sign in to add a reply."); const { error } = await db.from("community_posts").insert({ topic_id: topic.id, author_id: auth.user.id, body: body.trim(), moderation_state: "pending" }); if (error) return setStatus(error.message); setBody(""); setStatus("Reply submitted for moderator review."); }
  const voteButtons = (kind: "topic" | "post", id: string, score: number, current: number | null) => <div className="vote-controls"><button aria-label="Upvote" className={current === 1 ? "selected" : ""} onClick={() => vote(kind, id, 1)}>+</button><strong>{score}</strong><button aria-label="Downvote" className={current === -1 ? "selected" : ""} onClick={() => vote(kind, id, -1)}>−</button></div>;
  if (!topic) return <main className="content-page wrap"><p>{status}</p></main>;
  return <main className="content-page wrap"><article className="reading topic-reading"><Link className="back-link" href="/community">← Community</Link><p className="eyebrow">{topic.community_categories?.name} · {new Date(topic.created_at).toLocaleDateString()}</p><div className="topic-title-row"><h1>{topic.title}</h1>{voteButtons("topic", topic.id, topic.score, topicVote)}</div><p>{topic.body}</p><Link className="inline-cta" href={`/issues?source_topic=${topic.id}`}>Turn this thread into a service case</Link></article><section className="replies"><h2>Replies</h2>{posts.map((post) => <article key={post.id}><div><p>{post.body}</p><small>{new Date(post.created_at).toLocaleDateString()}</small></div>{voteButtons("post", post.id, post.score, votes[post.id] ?? null)}</article>)}{topic.moderation_state === "locked" ? <p className="empty-copy">This conversation is closed to new replies.</p> : <form className="community-form" onSubmit={reply}><label>Add your experience<textarea required minLength={2} maxLength={10000} value={body} onChange={(event) => setBody(event.target.value)} placeholder="Share what worked, or ask a useful follow-up." /></label><button type="submit">Submit reply</button></form>}<p className="directory-status">{status}</p></section></main>;
}
