"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import { AdminNavigation } from "@/app/portal-navigation";

type Request = { id: string; created_at: string; proposed_profile: Record<string, unknown>; proposed_vehicle_ids: string[]; proposed_repair_types: string[]; proposed_certification_ids: string[]; proposed_images: Array<{ storage_path: string; alt_text: string }>; };
export default function AdminPage() {
  const router = useRouter(); const [db] = useState(() => isSupabaseConfigured ? createBrowserSupabaseClient() : null); const [requests, setRequests] = useState<Request[]>([]); const [imageUrls, setImageUrls] = useState<Record<string, string>>({}); const [ready, setReady] = useState(false); const [message, setMessage] = useState("");
  const load = useCallback(async () => { if (!db) return; const { data, error } = await db.from("shop_change_requests").select("id,created_at,proposed_profile,proposed_vehicle_ids,proposed_repair_types,proposed_certification_ids,proposed_images").eq("status", "pending").order("created_at"); if (error) setMessage(error.message); else { const pending = (data ?? []) as Request[]; const urls = await Promise.all(pending.flatMap((request) => request.proposed_images.map(async (image) => [image.storage_path, (await db.storage.from("shop-images").createSignedUrl(image.storage_path, 3600)).data?.signedUrl ?? ""] as const))); setRequests(pending); setImageUrls(Object.fromEntries(urls.filter(([, url]) => url))); } }, [db]);
  useEffect(() => { if (!db) return; db.auth.getUser().then(async ({ data, error: authError }) => { if (authError) return setMessage("We could not verify your sign-in. Please try again."); if (!data.user) return router.replace("/"); const { data: profile, error: profileError } = await db.from("profiles").select("is_admin").eq("id", data.user.id).maybeSingle(); if (profileError) return setMessage("Administrator access could not be verified. Please try again."); if (!profile?.is_admin) return router.replace("/portal"); setReady(true); void load(); }); }, [db, load, router]);
  async function review(id: string, approved: boolean) { if (!db) return; const note = approved ? null : window.prompt("Optional rejection note") ?? null; const { error } = approved ? await db.rpc("approve_shop_change", { request_id: id }) : await db.rpc("reject_shop_change", { request_id: id, note }); if (error) setMessage(error.message); else { setMessage(approved ? "Request approved and published." : "Request rejected."); load(); } }
  if (!isSupabaseConfigured) return <main className="portal">Supabase is not configured.</main>;
  if (!ready) return <main className="portal">{message || "Checking administrator access..."}</main>;
  return <main className="portal"><section className="portal-head"><p className="eyebrow">Shop administration</p><h1>Review submissions.</h1><p>{requests.length} pending request{requests.length === 1 ? "" : "s"}.</p></section><AdminNavigation />{message && <p className="form-message">{message}</p>}<section className="admin-list">{requests.map((request) => <article className="admin-shop" key={request.id}><div><strong>Submitted {new Date(request.created_at).toLocaleDateString()}</strong><span>Pending</span></div><h2>{String(request.proposed_profile.name || "Unnamed shop")}</h2><p>{String(request.proposed_profile.address || "")}, {String(request.proposed_profile.city || "")}, {String(request.proposed_profile.state || "")}</p><p>{String(request.proposed_profile.description || "No description provided.")}</p><p><b>Vehicles:</b> {request.proposed_vehicle_ids.length} · <b>Repairs:</b> {request.proposed_repair_types.map((item) => item.replaceAll("_", " ")).join(", ") || "None"} · <b>Certifications:</b> {request.proposed_certification_ids.length}</p><div className="request-images">{request.proposed_images.map((image) => { if (!imageUrls[image.storage_path]) return null; // This private Storage URL expires, so next/image cannot optimize it safely.
              // eslint-disable-next-line @next/next/no-img-element
              return <img key={image.storage_path} src={imageUrls[image.storage_path]} alt={image.alt_text || "Shop submission"} />; })}</div><div className="review-actions"><button onClick={() => review(request.id, true)}>Approve</button><button className="reject" onClick={() => review(request.id, false)}>Reject</button></div></article>)}</section>{!requests.length && <p className="empty-copy">No shop submissions are awaiting review.</p>}</main>;
}
