"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";

type Shop = { id: string; name: string; address: string | null; city: string; state: string | null; phone: string | null; website: string | null; hours: string | null; description: string | null; bay_count: number | null; years_in_business: number | null; service_territory: string | null; partner_type: { name: string }[] };
export default function ShopPage() {
  const { id } = useParams<{ id: string }>(); const [shop, setShop] = useState<Shop | null>(null); const [vehicles, setVehicles] = useState<string[]>([]); const [capabilities, setCapabilities] = useState<string[]>([]); const [certifications, setCertifications] = useState<string[]>([]); const [images, setImages] = useState<Array<{ storage_path: string; alt_text: string | null }>>([]); const [missing, setMissing] = useState(false);
  useEffect(() => { if (!isSupabaseConfigured) return setMissing(true); const db = createBrowserSupabaseClient(); db.from("shops").select("id,name,address,city,state,phone,website,hours,description,bay_count,years_in_business,service_territory,partner_type:partner_types(name)").eq("id", id).single().then(async ({ data, error }) => { if (error || !data) return setMissing(true); setShop(data as Shop); const [vehicleRows, capabilityRows, certificationRows, imageRows] = await Promise.all([db.from("shop_vehicles").select("vehicle_id").eq("shop_id", id), db.from("partner_capabilities").select("capability_id").eq("shop_id", id), db.from("shop_certifications").select("certification_id").eq("shop_id", id), db.from("shop_images").select("storage_path,alt_text").eq("shop_id", id).order("is_primary", { ascending: false }).order("sort_order")]); const vehicleIds = vehicleRows.data?.map((row) => row.vehicle_id) ?? []; const capabilityIds = capabilityRows.data?.map((row) => row.capability_id) ?? []; const certificationIds = certificationRows.data?.map((row) => row.certification_id) ?? []; const [vehicleData, capabilityData, certificationData] = await Promise.all([vehicleIds.length ? db.from("vehicle_catalog").select("make,model").in("id", vehicleIds) : Promise.resolve({ data: [] }), capabilityIds.length ? db.from("service_capabilities").select("name").in("id", capabilityIds) : Promise.resolve({ data: [] }), certificationIds.length ? db.from("certifications").select("name").in("id", certificationIds) : Promise.resolve({ data: [] })]); setVehicles(vehicleData.data?.map((vehicle) => `${vehicle.make} ${vehicle.model}`) ?? []); setCapabilities(capabilityData.data?.map((capability) => capability.name) ?? []); setCertifications(certificationData.data?.map((certification) => certification.name) ?? []); setImages(imageRows.data ?? []); }); }, [id]);
  if (missing) return <main className="portal"><h1>Partner not found.</h1></main>;
  if (!shop) return <main className="portal">Loading partner...</main>;
  const db = createBrowserSupabaseClient(); const imageUrl = (path: string) => db.storage.from("shop-images").getPublicUrl(path).data.publicUrl;
  return <main className="shop-detail"><section className="shop-hero wrap"><p className="eyebrow">{shop.partner_type[0]?.name ?? "Independent EV service"}</p><h1>{shop.name}</h1><p>{[shop.address, shop.city, shop.state].filter(Boolean).join(", ")}</p>{shop.description && <p className="intro">{shop.description}</p>}{shop.phone && <a href={`tel:${shop.phone}`}>{shop.phone}</a>}{shop.website && <a href={shop.website} target="_blank" rel="noreferrer">Visit website</a>}</section>{images.length > 0 && <section className="shop-gallery wrap">{images.map((image) => <img key={image.storage_path} src={imageUrl(image.storage_path)} alt={image.alt_text || shop.name} />)}</section>}<section className="shop-info wrap"><div><h2>Capabilities</h2><p>{capabilities.join(", ") || "Contact this partner for services."}</p></div><div><h2>Vehicles</h2><p>{vehicles.join(", ") || "Vehicle-independent service."}</p></div><div><h2>Credentials</h2><p>{certifications.join(", ") || "No certifications listed."}</p></div><div><h2>Service details</h2><p>{shop.service_territory && `Serves ${shop.service_territory} · `}{shop.hours || "Hours not listed"}{shop.bay_count ? ` · ${shop.bay_count} bays` : ""}{shop.years_in_business ? ` · ${shop.years_in_business} years in business` : ""}</p></div></section></main>;
}
