"use client";
import Link from "@/app/locale-link";
import { FormEvent, useEffect, useState } from "react";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
type Case = { id: string; title: string; symptoms: string; warning_codes: string | null; vehicle_year: number | null; vehicle_make: string | null; vehicle_model: string | null; source_topic_id: string | null; status: string };
type Response = { body: string; created_at: string };
export default function IssuePage({ params }: { params: Promise<{ id: string }> }) {
  const [issue, setIssue] = useState<Case | null>(null); const [response, setResponse] = useState<Response | null>(null); const [status, setStatus] = useState("Loading your case...");
  const load = async (id: string) => { if (!isSupabaseConfigured) return setStatus("Issue workspace is not configured."); const db = createBrowserSupabaseClient(); const { data, error } = await db.from("issue_cases").select("id,title,symptoms,warning_codes,vehicle_year,vehicle_make,vehicle_model,source_topic_id,status").eq("id", id).maybeSingle(); if (error || !data) return setStatus("This case is unavailable."); setIssue(data as Case); const { data: opportunity } = await db.from("expert_opportunities").select("id").eq("case_id", id).eq("status", "answered").maybeSingle(); if (opportunity) { const { data: expert } = await db.from("expert_responses").select("body,created_at").eq("opportunity_id", opportunity.id).maybeSingle(); setResponse(expert as Response | null); } setStatus(""); };
  useEffect(() => { void params.then(({ id }) => load(id)); }, [params]);
  async function pathway(pathway: string) { if (!issue) return; const db = createBrowserSupabaseClient(); if (pathway === "service") { const { error } = await db.rpc("create_case_service_request", { case_id: issue.id, source_topic_id: issue.source_topic_id }); setStatus(error ? error.message : "Service request created with your complete case context."); return; } if (pathway === "expert") { const { data: auth } = await db.auth.getUser(); if (!auth.user) return setStatus("Sign in to request an expert response."); const { data: profile } = await db.from("profiles").select("membership_tier").eq("id", auth.user.id).maybeSingle(); if (profile?.membership_tier !== "premium") return setStatus("Premium membership is required for a paid expert response."); const { error } = await db.from("expert_opportunities").insert({ case_id: issue.id, owner_id: auth.user.id }); setStatus(error ? error.message : "Premium expert opportunity posted for verified mechanics."); return; } const { error } = await db.from("issue_pathway_events").insert({ case_id: issue.id, pathway, detail: `Viewed ${pathway} pathway` }); setStatus(error ? error.message : "Pathway saved to your case."); }
  if (!issue) return <main className="content-page wrap"><p>{status}</p></main>;
  return <main className="content-page wrap"><article className="reading issue-reading"><Link className="back-link" href="/issues">← My issues</Link><p className="eyebrow">{issue.status} · {issue.vehicle_year} {issue.vehicle_make} {issue.vehicle_model}</p><h1>{issue.title}</h1><p>{issue.symptoms}</p>{issue.warning_codes && <p><b>Warnings:</b> {issue.warning_codes}</p>}</article><section className="pathway-grid"><article><h2>Search results</h2><p>Find specialists who support your vehicle and diagnosis.</p><Link href="/shops" onClick={() => pathway("search")}>Search shops →</Link></article><article><h2>DIY check</h2><p>Use safe, practical checks before booking a bay.</p><Link href="/tutorials" onClick={() => pathway("diy")}>Open DIY guides →</Link></article><article><h2>Community</h2><p>Compare notes with other EV owners.</p><Link href="/community" onClick={() => pathway("community")}>Ask the community →</Link></article><article><h2>Service pathway</h2><p>Send your vehicle, symptoms, media, and linked thread as one request.</p><button onClick={() => pathway("service")}>Request service</button></article><article><h2>Premium expert</h2><p>A verified mechanic can claim a paid opportunity and reply in this case.</p><button onClick={() => pathway("expert")}>Request expert response</button></article></section>{response && <section className="expert-answer"><p className="eyebrow">Expert response</p><p>{response.body}</p></section>}<p className="directory-status">{status}</p></main>;
}
