"use client";
import { FormEvent, useEffect, useState } from "react";
import { createBrowserSupabaseClient, isSupabaseConfigured } from "@/lib/supabase";
import { Button, PageHeader } from "@/app/page-primitives";
type Opportunity = { id: string; case_id: string; payout_cents: number; status: string; expert_id: string | null };
export default function ExpertWorkPage() {
  const [jobs, setJobs] = useState<Opportunity[]>([]); const [message, setMessage] = useState(""); const [draft, setDraft] = useState<Record<string, string>>({});
  const load = () => { if (!isSupabaseConfigured) return; createBrowserSupabaseClient().from("expert_opportunities").select("id,case_id,payout_cents,status,expert_id").in("status", ["open", "claimed"]).order("created_at").then(({ data, error }) => { setJobs((data ?? []) as Opportunity[]); if (error) setMessage(error.message); }); }; useEffect(load, []);
  async function claim(id: string) { const { data, error } = await createBrowserSupabaseClient().rpc("claim_expert_opportunity", { opportunity_id: id }); setMessage(error ? error.message : data ? "Opportunity claimed. Review its private case details, then answer below." : "This opportunity was already claimed."); load(); }
  async function answer(event: FormEvent, job: Opportunity) { event.preventDefault(); const { error } = await createBrowserSupabaseClient().rpc("submit_expert_response", { opportunity_id: job.id, response_body: draft[job.id] || "" }); setMessage(error?.message || "Response sent; payout job remains pending for administration."); load(); }
  return <main className="content-page wrap"><PageHeader className="content-head" eyebrow="Mechanic expert work" title="Respond with context, get paid transparently." intro="Only shop owners can claim opportunities. Payout records are admin-managed and do not initiate a Stripe Connect transfer." /><p className="directory-status">{message}</p><section className="topic-list">{jobs.map((job) => <article className="topic-card" key={job.id}><p className="eyebrow">{job.status} · ${(job.payout_cents / 100).toFixed(2)} payout</p><h2>Issue expert opportunity</h2>{job.status === "open" ? <Button onClick={() => claim(job.id)}>Claim opportunity</Button> : <form className="community-form" onSubmit={(event) => answer(event, job)}><label>Expert response<textarea required minLength={20} value={draft[job.id] || ""} onChange={(event) => setDraft({ ...draft, [job.id]: event.target.value })} /></label><Button>Send response</Button></form>}</article>)}</section></main>;
}
