-- Explain why Amped Up Network exists before asking owners to choose a journey.
insert into public.localized_content (content_key, locale, value) values
  ('home.title','en','Your EV ownership network, {{accent}}'),('home.title','de','Ihr Netzwerk für EV-Besitz, {{accent}}'),('home.title','fr','Votre réseau pour la propriété d''un VE, {{accent}}'),('home.title','es','Tu red para tener un VE, {{accent}}'),
  ('home.title_accent','en','finally'),('home.title_accent','de','endlich'),('home.title_accent','fr','enfin'),('home.title_accent','es','por fin'),
  ('home.intro','en','Amped Up Network is a focused home for EV owners to find real answers, capable local help, community knowledge, and practical next steps.'),('home.intro','de','Amped Up Network ist ein fokussiertes Zuhause für EV-Eigentümer, um echte Antworten, kompetente Hilfe vor Ort, Community-Wissen und praktische nächste Schritte zu finden.'),('home.intro','fr','Amped Up Network est un lieu dédié aux propriétaires de VE pour trouver de vraies réponses, une aide locale compétente, les connaissances de la communauté et des prochaines étapes pratiques.'),('home.intro','es','Amped Up Network es un espacio enfocado para propietarios de VE que buscan respuestas reales, ayuda local capacitada, conocimiento de la comunidad y próximos pasos prácticos.'),
  ('home.journey_title','en','More than a directory. More than a store. More than a forum.'),('home.journey_title','de','Mehr als ein Verzeichnis. Mehr als ein Shop. Mehr als ein Forum.'),('home.journey_title','fr','Plus qu''un annuaire. Plus qu''une boutique. Plus qu''un forum.'),('home.journey_title','es','Más que un directorio. Más que una tienda. Más que un foro.'),
  ('home.journey_guided','en','Find EV-capable mechanics, alignment shops, electricians, and aftermarket specialists that are hard to discover elsewhere.'),('home.journey_guided','de','Finden Sie EV-erfahrene Werkstätten, Achsvermessungsbetriebe, Elektriker und Aftermarket-Spezialisten, die sonst schwer zu entdecken sind.'),('home.journey_guided','fr','Trouvez des mécaniciens, ateliers de géométrie, électriciens et spécialistes de l''après-vente compétents en VE, difficiles à découvrir ailleurs.'),('home.journey_guided','es','Encuentra mecánicos, talleres de alineación, electricistas y especialistas posventa capacitados en VE que son difíciles de descubrir en otros lugares.'),
  ('home.journey_community','en','Get focused recommendations, training, products, and services instead of piecing together social media and web searches.'),('home.journey_community','de','Erhalten Sie gezielte Empfehlungen, Schulungen, Produkte und Services, statt soziale Medien und Websuchen zusammensetzen zu müssen.'),('home.journey_community','fr','Obtenez des recommandations, formations, produits et services ciblés au lieu de reconstituer les réponses depuis les réseaux sociaux et le web.'),('home.journey_community','es','Obtén recomendaciones, formación, productos y servicios enfocados en lugar de armar respuestas desde redes sociales y búsquedas web.'),
  ('home.journey_expert','en','Ask a community built for EV ownership, where owners and experts share practical knowledge.'),('home.journey_expert','de','Fragen Sie eine Community, die für EV-Besitz geschaffen ist und in der Eigentümer und Experten praktisches Wissen teilen.'),('home.journey_expert','fr','Posez vos questions à une communauté conçue pour la propriété d''un VE, où propriétaires et experts partagent des connaissances pratiques.'),('home.journey_expert','es','Pregunta a una comunidad creada para tener un VE, donde propietarios y expertos comparten conocimiento práctico.'),
  ('home.journey_service','en','Carry your vehicle, problem, purchase, and post history forward so every next step starts with context.'),('home.journey_service','de','Nehmen Sie Ihren Fahrzeug-, Problem-, Kauf- und Beitragsverlauf mit, damit jeder nächste Schritt mit Kontext beginnt.'),('home.journey_service','fr','Conservez l''historique de votre véhicule, problème, achat et publication pour que chaque étape suivante commence avec le bon contexte.'),('home.journey_service','es','Conserva el historial de tu vehículo, problema, compra y publicación para que cada siguiente paso comience con contexto.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
