-- Describe the planned partner programs and commercial model without publishing figures or earnings promises.
insert into public.localized_content (content_key, locale, value) values
  ('partnership.levels_eyebrow','en','Programs that match your work'),
  ('partnership.levels_eyebrow','de','Programme, die zu Ihrer Arbeit passen'),
  ('partnership.levels_eyebrow','fr','Des programmes adaptés à votre travail'),
  ('partnership.levels_eyebrow','es','Programas que se adaptan a tu trabajo'),
  ('partnership.levels_title','en','Built around your specialty and readiness.'),
  ('partnership.levels_title','de','Auf Ihre Spezialisierung und Bereitschaft abgestimmt.'),
  ('partnership.levels_title','fr','Conçu autour de votre spécialité et de votre préparation.'),
  ('partnership.levels_title','es','Diseñado según tu especialidad y preparación.'),
  ('partnership.levels_intro','en','The level we discuss depends on your partner class, evidence, and the program standards available for your work.'),
  ('partnership.levels_intro','de','Die besprochene Stufe hängt von Ihrer Partnerklasse, Ihren Nachweisen und den für Ihre Arbeit verfügbaren Programmstandards ab.'),
  ('partnership.levels_intro','fr','Le niveau dont nous discutons dépend de votre catégorie de partenaire, de vos preuves et des normes de programme disponibles pour votre travail.'),
  ('partnership.levels_intro','es','El nivel que analizamos depende de tu clase de socio, evidencia y los estándares del programa disponibles para tu trabajo.'),
  ('partnership.level_specialist','en','Verified Specialty / Infrastructure'),
  ('partnership.level_specialist','de','Verifizierter Spezialist / Infrastruktur'),
  ('partnership.level_specialist','fr','Spécialiste / infrastructure vérifié'),
  ('partnership.level_specialist','es','Especialista / infraestructura verificada'),
  ('partnership.level_specialist_intro','en','For electrical, charging, appearance, protection, and aftermarket businesses. We verify the business, required credentials, service scope, and profile details for the partner class.'),
  ('partnership.level_specialist_intro','de','Für Unternehmen aus Elektrik, Laden, Fahrzeugoptik, Schutz und Aftermarket. Wir prüfen das Unternehmen, erforderliche Nachweise, Leistungsumfang und Profildetails für die Partnerklasse.'),
  ('partnership.level_specialist_intro','fr','Pour les entreprises d''électricité, de recharge, d''esthétique, de protection et d''après-vente. Nous vérifions l''entreprise, les qualifications requises, le périmètre de service et les détails du profil pour la catégorie de partenaire.'),
  ('partnership.level_specialist_intro','es','Para negocios de electricidad, carga, estética, protección y posventa. Verificamos el negocio, credenciales requeridas, alcance de servicio y detalles del perfil para la clase de socio.'),
  ('partnership.level_certified','en','Certified Partner'),
  ('partnership.level_certified','de','Zertifizierter Partner'),
  ('partnership.level_certified','fr','Partenaire certifié'),
  ('partnership.level_certified','es','Socio certificado'),
  ('partnership.level_certified_intro','en','Reserved for core EV repair partners that complete the network''s readiness, safety, training, warranty, and customer-experience standards.'),
  ('partnership.level_certified_intro','de','Reserviert für Kern-EV-Reparaturpartner, die die Standards des Netzwerks für Bereitschaft, Sicherheit, Schulung, Garantie und Kundenerfahrung erfüllen.'),
  ('partnership.level_certified_intro','fr','Réservé aux partenaires de réparation VE qui satisfont aux normes du réseau en matière de préparation, sécurité, formation, garantie et expérience client.'),
  ('partnership.level_certified_intro','es','Reservado para socios de reparación principal de VE que cumplen los estándares de preparación, seguridad, capacitación, garantía y experiencia del cliente de la red.'),
  ('partnership.level_leader','en','Network Leader'),
  ('partnership.level_leader','de','Netzwerkleiter'),
  ('partnership.level_leader','fr','Leader du réseau'),
  ('partnership.level_leader','es','Líder de la red'),
  ('partnership.level_leader_intro','en','For established Certified Partners with sustained outcomes and a meaningful contribution to education, events, and the local EV community.'),
  ('partnership.level_leader_intro','de','Für etablierte zertifizierte Partner mit nachhaltigen Ergebnissen und einem bedeutenden Beitrag zu Bildung, Veranstaltungen und der lokalen EV-Community.'),
  ('partnership.level_leader_intro','fr','Pour les partenaires certifiés établis avec des résultats durables et une contribution significative à l''éducation, aux événements et à la communauté VE locale.'),
  ('partnership.level_leader_intro','es','Para socios certificados establecidos con resultados sostenidos y una contribución significativa a la educación, eventos y comunidad local de VE.'),
  ('partnership.commercial_eyebrow','en','Clear commercial terms'),
  ('partnership.commercial_eyebrow','de','Klare kommerzielle Bedingungen'),
  ('partnership.commercial_eyebrow','fr','Des conditions commerciales claires'),
  ('partnership.commercial_eyebrow','es','Términos comerciales claros'),
  ('partnership.commercial_title','en','Know how the program works before you join.'),
  ('partnership.commercial_title','de','Wissen Sie vor dem Beitritt, wie das Programm funktioniert.'),
  ('partnership.commercial_title','fr','Comprenez le fonctionnement du programme avant de nous rejoindre.'),
  ('partnership.commercial_title','es','Conoce cómo funciona el programa antes de unirte.'),
  ('partnership.commercial_intro','en','We discuss the right track, responsibilities, and terms before enrollment. We do not promise lead volume, earnings, or certification.'),
  ('partnership.commercial_intro','de','Wir besprechen vor der Teilnahme den passenden Weg, Verantwortlichkeiten und Bedingungen. Wir versprechen weder Auftragsvolumen, Einnahmen noch Zertifizierung.'),
  ('partnership.commercial_intro','fr','Nous discutons du parcours approprié, des responsabilités et des conditions avant l''inscription. Nous ne promettons ni volume de prospects, ni revenus, ni certification.'),
  ('partnership.commercial_intro','es','Analizamos el camino adecuado, responsabilidades y términos antes de la inscripción. No prometemos volumen de clientes potenciales, ganancias ni certificación.'),
  ('partnership.commercial_launch','en','Launch support'),
  ('partnership.commercial_launch','de','Launch-Unterstützung'),
  ('partnership.commercial_launch','fr','Accompagnement de lancement'),
  ('partnership.commercial_launch','es','Apoyo de lanzamiento'),
  ('partnership.commercial_launch_intro','en','Your launch track is matched to your work. It may include profile development, scope and credential review, customer-experience preparation, and class-appropriate launch support.'),
  ('partnership.commercial_launch_intro','de','Ihr Launch-Weg wird auf Ihre Arbeit abgestimmt. Er kann Profilentwicklung, Prüfung von Umfang und Nachweisen, Vorbereitung der Kundenerfahrung und klassenbezogene Launch-Unterstützung umfassen.'),
  ('partnership.commercial_launch_intro','fr','Votre parcours de lancement est adapté à votre travail. Il peut inclure le développement du profil, l''examen du périmètre et des qualifications, la préparation de l''expérience client et un accompagnement de lancement adapté à votre catégorie.'),
  ('partnership.commercial_launch_intro','es','Tu ruta de lanzamiento se adapta a tu trabajo. Puede incluir desarrollo de perfil, revisión de alcance y credenciales, preparación de experiencia del cliente y apoyo de lanzamiento apropiado para tu clase.'),
  ('partnership.commercial_ongoing','en','Ongoing participation'),
  ('partnership.commercial_ongoing','de','Laufende Teilnahme'),
  ('partnership.commercial_ongoing','fr','Participation continue'),
  ('partnership.commercial_ongoing','es','Participación continua'),
  ('partnership.commercial_ongoing_intro','en','Ongoing terms align with your program level and are set out before enrollment. Completed-booking fees apply only to qualifying work where that model is used.'),
  ('partnership.commercial_ongoing_intro','de','Laufende Bedingungen richten sich nach Ihrer Programmstufe und werden vor der Teilnahme festgelegt. Gebühren für abgeschlossene Buchungen gelten nur für qualifizierende Arbeit, bei der dieses Modell verwendet wird.'),
  ('partnership.commercial_ongoing_intro','fr','Les conditions continues sont alignées sur votre niveau de programme et définies avant l''inscription. Les frais de réservation finalisée ne s''appliquent qu''au travail admissible lorsque ce modèle est utilisé.'),
  ('partnership.commercial_ongoing_intro','es','Los términos continuos se alinean con tu nivel de programa y se establecen antes de la inscripción. Las tarifas por reservas completadas se aplican solo al trabajo que califica cuando se utiliza ese modelo.'),
  ('partnership.commercial_payout','en','Paid work and expert contributions'),
  ('partnership.commercial_payout','de','Bezahlte Arbeit und Expertenbeiträge'),
  ('partnership.commercial_payout','fr','Travail rémunéré et contributions d''experts'),
  ('partnership.commercial_payout','es','Trabajo remunerado y contribuciones de expertos'),
  ('partnership.commercial_payout_intro','en','When paid managed-service or expert work is offered, the scope and partner payout are disclosed before acceptance. Payout records are administered manually; automated transfers are not available.'),
  ('partnership.commercial_payout_intro','de','Wenn bezahlte Managed-Service- oder Expertenarbeit angeboten wird, werden Umfang und Partnervergütung vor der Annahme offengelegt. Auszahlungsaufzeichnungen werden manuell verwaltet; automatisierte Überweisungen sind nicht verfügbar.'),
  ('partnership.commercial_payout_intro','fr','Lorsqu''un service géré ou un travail d''expert rémunéré est proposé, le périmètre et le paiement du partenaire sont communiqués avant acceptation. Les paiements sont administrés manuellement ; les transferts automatisés ne sont pas disponibles.'),
  ('partnership.commercial_payout_intro','es','Cuando se ofrece trabajo remunerado de servicio gestionado o experto, el alcance y el pago al socio se informan antes de la aceptación. Los registros de pago se administran manualmente; las transferencias automatizadas no están disponibles.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
