-- Localized copy for the integrated partner-program marketing narrative.
insert into public.localized_content (content_key, locale, value) values
  ('partnership.title','en','Your brand. Your shop.'),
  ('partnership.title','de','Ihre Marke. Ihr Betrieb.'),
  ('partnership.title','fr','Votre marque. Votre atelier.'),
  ('partnership.title','es','Tu marca. Tu taller.'),
  ('partnership.case_title','en','Connecting qualified clients to qualified shops.'),
  ('partnership.case_title','de','Qualifizierte Kunden mit qualifizierten Betrieben verbinden.'),
  ('partnership.case_title','fr','Mettre en relation des clients qualifiés avec des ateliers qualifiés.'),
  ('partnership.case_title','es','Conectamos clientes calificados con talleres calificados.'),
  ('partnership.chapter_front_door_eyebrow','en','01 / Build your front door'),
  ('partnership.chapter_front_door_eyebrow','de','01 / Bauen Sie Ihre Eingangstür'),
  ('partnership.chapter_front_door_eyebrow','fr','01 / Construisez votre porte d''entrée'),
  ('partnership.chapter_front_door_eyebrow','es','01 / Construye tu puerta de entrada'),
  ('partnership.chapter_front_door_title','en','Start with the truth about what your business does best.'),
  ('partnership.chapter_front_door_title','de','Beginnen Sie mit der Wahrheit darüber, was Ihr Unternehmen am besten kann.'),
  ('partnership.chapter_front_door_title','fr','Commencez par la vérité sur ce que votre entreprise fait le mieux.'),
  ('partnership.chapter_front_door_title','es','Comienza con la verdad sobre lo que tu negocio hace mejor.'),
  ('partnership.chapter_front_door_intro','en','Your application captures your service area, EV experience, credentials, scope, and supported vehicles. We review the evidence required for your class, then help shape a credible profile, defined offer, and class-appropriate launch plan before it is published.'),
  ('partnership.chapter_front_door_intro','de','Ihr Antrag erfasst Ihr Einsatzgebiet, Ihre EV-Erfahrung, Nachweise, Ihren Leistungsumfang und unterstützte Fahrzeuge. Wir prüfen die für Ihre Klasse erforderlichen Nachweise und helfen dann, ein glaubwürdiges Profil, ein definiertes Angebot und einen klassenbezogenen Launch-Plan zu gestalten, bevor er veröffentlicht wird.'),
  ('partnership.chapter_front_door_intro','fr','Votre candidature présente votre zone de service, votre expérience VE, vos qualifications, votre périmètre et les véhicules pris en charge. Nous examinons les preuves requises pour votre catégorie, puis aidons à façonner un profil crédible, une offre définie et un plan de lancement adapté avant sa publication.'),
  ('partnership.chapter_front_door_intro','es','Tu solicitud reúne tu área de servicio, experiencia en VE, credenciales, alcance y vehículos compatibles. Revisamos la evidencia necesaria para tu clase y luego ayudamos a crear un perfil creíble, una oferta definida y un plan de lanzamiento adecuado antes de publicarlo.'),
  ('partnership.chapter_growth_eyebrow','en','02 / Market yourself by participating'),
  ('partnership.chapter_growth_eyebrow','de','02 / Vermarkten Sie sich durch Teilnahme'),
  ('partnership.chapter_growth_eyebrow','fr','02 / Faites votre promotion en participant'),
  ('partnership.chapter_growth_eyebrow','es','02 / Promociónate participando'),
  ('partnership.chapter_growth_title','en','Turn real expertise into a stronger local reputation.'),
  ('partnership.chapter_growth_title','de','Machen Sie aus echter Expertise einen stärkeren lokalen Ruf.'),
  ('partnership.chapter_growth_title','fr','Transformez une véritable expertise en une réputation locale plus forte.'),
  ('partnership.chapter_growth_title','es','Convierte experiencia real en una reputación local más sólida.'),
  ('partnership.chapter_growth_intro','en','Your profile is only the start. Partners market their own brand through helpful community participation, education, local events, and clear EV-specific service information. Training, verified outcomes, and sustained contribution create a path to higher program levels when available.'),
  ('partnership.chapter_growth_intro','de','Ihr Profil ist nur der Anfang. Partner vermarkten ihre eigene Marke durch hilfreiche Community-Teilnahme, Bildung, lokale Veranstaltungen und klare EV-spezifische Serviceinformationen. Training, verifizierte Ergebnisse und nachhaltige Beiträge schaffen einen Weg zu höheren Programmstufen, wenn diese verfügbar sind.'),
  ('partnership.chapter_growth_intro','fr','Votre profil n''est qu''un début. Les partenaires font la promotion de leur propre marque grâce à une participation utile à la communauté, à l''éducation, aux événements locaux et à des informations de service VE claires. La formation, les résultats vérifiés et une contribution durable créent un chemin vers des niveaux de programme supérieurs lorsqu''ils sont disponibles.'),
  ('partnership.chapter_growth_intro','es','Tu perfil es solo el comienzo. Los socios promocionan su propia marca mediante participación útil en la comunidad, educación, eventos locales e información clara de servicios específicos para VE. La capacitación, resultados verificados y contribución sostenida crean un camino hacia niveles superiores del programa cuando están disponibles.'),
  ('partnership.chapter_terms_eyebrow','en','03 / Work from clear terms'),
  ('partnership.chapter_terms_eyebrow','de','03 / Arbeiten Sie nach klaren Bedingungen'),
  ('partnership.chapter_terms_eyebrow','fr','03 / Travaillez selon des conditions claires'),
  ('partnership.chapter_terms_eyebrow','es','03 / Trabaja con términos claros'),
  ('partnership.chapter_terms_title','en','Keep your customer relationship. Know the terms before you say yes.'),
  ('partnership.chapter_terms_title','de','Behalten Sie Ihre Kundenbeziehung. Kennen Sie die Bedingungen, bevor Sie zustimmen.'),
  ('partnership.chapter_terms_title','fr','Conservez votre relation client. Connaissez les conditions avant de dire oui.'),
  ('partnership.chapter_terms_title','es','Conserva tu relación con el cliente. Conoce los términos antes de aceptar.'),
  ('partnership.chapter_terms_intro','en','For direct referrals, your shop quotes, contracts, bills, and warranties the work. We discuss launch, participation, booking, managed-service, and expert-work terms in advance, with no promises of lead volume, earnings, or certification.'),
  ('partnership.chapter_terms_intro','de','Bei direkten Empfehlungen erstellt Ihr Betrieb Angebote, schließt Verträge, stellt Rechnungen und gewährleistet die Arbeit. Wir besprechen Launch-, Teilnahme-, Buchungs-, Managed-Service- und Expertenarbeitsbedingungen im Voraus, ohne Versprechen zu Auftragsvolumen, Einnahmen oder Zertifizierung.'),
  ('partnership.chapter_terms_intro','fr','Pour les recommandations directes, votre atelier établit les devis, contrats, factures et garanties. Nous discutons à l''avance des conditions de lancement, participation, réservation, service géré et travail d''expert, sans promesse de volume de prospects, revenus ou certification.'),
  ('partnership.chapter_terms_intro','es','Para referencias directas, tu taller cotiza, contrata, factura y garantiza el trabajo. Analizamos por adelantado los términos de lanzamiento, participación, reservas, servicios gestionados y trabajo experto, sin promesas de volumen de clientes potenciales, ganancias o certificación.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
