-- Explain the four entry journeys and their connected next steps in every locale.
insert into public.localized_content (content_key, locale, value) values
  ('home.paths_eyebrow','en','Start where you are'),('home.paths_eyebrow','de','Starten Sie dort, wo Sie gerade sind'),('home.paths_eyebrow','fr','Commencez là où vous en êtes'),('home.paths_eyebrow','es','Empieza donde estás'),
  ('home.paths_title','en','Choose a path. We carry the context forward.'),('home.paths_title','de','Wählen Sie einen Weg. Wir nehmen den Kontext mit.'),('home.paths_title','fr','Choisissez un chemin. Nous conservons le contexte.'),('home.paths_title','es','Elige un camino. Conservamos el contexto.'),
  ('home.paths_intro','en','Every journey connects your vehicle, questions, and progress to the next useful resource.'),('home.paths_intro','de','Jeder Weg verbindet Ihr Fahrzeug, Ihre Fragen und Ihren Fortschritt mit der nächsten hilfreichen Ressource.'),('home.paths_intro','fr','Chaque parcours relie votre véhicule, vos questions et vos progrès à la prochaine ressource utile.'),('home.paths_intro','es','Cada recorrido conecta tu vehículo, tus preguntas y tu progreso con el siguiente recurso útil.'),
  ('home.path_issue_intro','en','Tell us what is happening. We organize the details, surface relevant answers, and help you choose a next step.'),('home.path_issue_intro','de','Sagen Sie uns, was passiert. Wir ordnen die Details, zeigen passende Antworten und helfen beim nächsten Schritt.'),('home.path_issue_intro','fr','Expliquez-nous ce qui se passe. Nous organisons les détails, faisons ressortir les réponses pertinentes et vous aidons à choisir la suite.'),('home.path_issue_intro','es','Cuéntanos qué está pasando. Organizamos los detalles, mostramos respuestas relevantes y te ayudamos a elegir el siguiente paso.'),
  ('home.path_maintenance_intro','en','Use training and checklists to build a practical plan, then carry it into a service visit when needed.'),('home.path_maintenance_intro','de','Nutzen Sie Schulungen und Checklisten für einen praktischen Plan und nehmen Sie ihn bei Bedarf zum Werkstatttermin mit.'),('home.path_maintenance_intro','fr','Utilisez des formations et des listes pour établir un plan pratique, puis apportez-le lors d''une visite d''atelier si nécessaire.'),('home.path_maintenance_intro','es','Usa formación y listas para crear un plan práctico y llévalo a una visita de servicio cuando sea necesario.'),
  ('home.path_catalog_intro','en','Compare community favorites and compatible options before you buy or book, with your vehicle context close at hand.'),('home.path_catalog_intro','de','Vergleichen Sie Community-Favoriten und passende Optionen vor dem Kauf oder der Buchung, mit Ihrem Fahrzeugkontext griffbereit.'),('home.path_catalog_intro','fr','Comparez les favoris de la communauté et les options compatibles avant d''acheter ou de réserver, avec le contexte de votre véhicule à portée de main.'),('home.path_catalog_intro','es','Compara favoritos de la comunidad y opciones compatibles antes de comprar o reservar, con el contexto de tu vehículo a mano.'),
  ('home.path_community_intro','en','Ask focused questions, learn from real ownership experience, and save what helps for next time.'),('home.path_community_intro','de','Stellen Sie gezielte Fragen, lernen Sie aus echten Eigentümererfahrungen und speichern Sie, was beim nächsten Mal hilft.'),('home.path_community_intro','fr','Posez des questions précises, apprenez de véritables expériences de propriétaires et enregistrez ce qui vous aidera la prochaine fois.'),('home.path_community_intro','es','Haz preguntas enfocadas, aprende de experiencias reales de propietarios y guarda lo que te ayude para la próxima vez.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
