-- Localized copy for the public partner onboarding entry point.
insert into public.localized_content (content_key, locale, value) values
  ('partnership.eyebrow','en','For EV businesses'),
  ('partnership.eyebrow','de','Für EV-Unternehmen'),
  ('partnership.eyebrow','fr','Pour les entreprises VE'),
  ('partnership.eyebrow','es','Para empresas de VE'),
  ('partnership.title','en','Bring your EV expertise to the network.'),
  ('partnership.title','de','Bringen Sie Ihre EV-Expertise ins Netzwerk.'),
  ('partnership.title','fr','Apportez votre expertise VE au réseau.'),
  ('partnership.title','es','Aporta tu experiencia en VE a la red.'),
  ('partnership.intro','en','Join a reviewed network where owners can find capable EV repair, electrical, appearance, and aftermarket specialists.'),
  ('partnership.intro','de','Treten Sie einem geprüften Netzwerk bei, in dem Eigentümer kompetente Spezialisten für EV-Reparatur, Elektrik, Fahrzeugoptik und Aftermarket finden.'),
  ('partnership.intro','fr','Rejoignez un réseau vérifié où les propriétaires trouvent des spécialistes compétents en réparation, électricité, esthétique et après-vente pour VE.'),
  ('partnership.intro','es','Únete a una red revisada donde los propietarios encuentran especialistas capaces en reparación, electricidad, estética y posventa de VE.'),
  ('partnership.action','en','Start your partner application'),
  ('partnership.action','de','Partnerantrag starten'),
  ('partnership.action','fr','Commencer votre candidature partenaire'),
  ('partnership.action','es','Inicia tu solicitud de socio'),
  ('partnership.steps_eyebrow','en','How it works'),
  ('partnership.steps_eyebrow','de','So funktioniert es'),
  ('partnership.steps_eyebrow','fr','Comment ça marche'),
  ('partnership.steps_eyebrow','es','Cómo funciona'),
  ('partnership.steps_title','en','A clear path into the network.'),
  ('partnership.steps_title','de','Ein klarer Weg ins Netzwerk.'),
  ('partnership.steps_title','fr','Un chemin clair vers le réseau.'),
  ('partnership.steps_title','es','Un camino claro hacia la red.'),
  ('partnership.step_apply','en','Apply'),
  ('partnership.step_apply','de','Bewerben'),
  ('partnership.step_apply','fr','Postuler'),
  ('partnership.step_apply','es','Solicita tu ingreso'),
  ('partnership.step_apply_intro','en','Tell us about your business, service area, EV experience, and the work you do.'),
  ('partnership.step_apply_intro','de','Erzählen Sie uns von Ihrem Unternehmen, Ihrem Einsatzgebiet, Ihrer EV-Erfahrung und Ihrer Arbeit.'),
  ('partnership.step_apply_intro','fr','Parlez-nous de votre entreprise, de votre zone de service, de votre expérience VE et de votre travail.'),
  ('partnership.step_apply_intro','es','Cuéntanos sobre tu negocio, área de servicio, experiencia en VE y el trabajo que haces.'),
  ('partnership.step_review','en','We review'),
  ('partnership.step_review','de','Wir prüfen'),
  ('partnership.step_review','fr','Nous examinons'),
  ('partnership.step_review','es','Revisamos'),
  ('partnership.step_review_intro','en','We review your profile and the credentials required for your partner type before publishing it.'),
  ('partnership.step_review_intro','de','Wir prüfen Ihr Profil und die für Ihren Partnertyp erforderlichen Nachweise, bevor wir es veröffentlichen.'),
  ('partnership.step_review_intro','fr','Nous examinons votre profil et les qualifications requises pour votre type de partenaire avant sa publication.'),
  ('partnership.step_review_intro','es','Revisamos tu perfil y las credenciales necesarias para tu tipo de socio antes de publicarlo.'),
  ('partnership.step_participate','en','You participate'),
  ('partnership.step_participate','de','Sie nehmen teil'),
  ('partnership.step_participate','fr','Vous participez'),
  ('partnership.step_participate','es','Participas'),
  ('partnership.step_participate_intro','en','Approved partners can be found by owners and take part in the network''s existing partner workflows.'),
  ('partnership.step_participate_intro','de','Zugelassene Partner können von Eigentümern gefunden werden und an den bestehenden Partnerabläufen des Netzwerks teilnehmen.'),
  ('partnership.step_participate_intro','fr','Les partenaires approuvés peuvent être trouvés par les propriétaires et participer aux flux partenaires existants du réseau.'),
  ('partnership.step_participate_intro','es','Los socios aprobados pueden ser encontrados por propietarios y participar en los flujos de socios existentes de la red.'),
  ('partnership.fit_eyebrow','en','Built for specialists'),
  ('partnership.fit_eyebrow','de','Für Spezialisten gemacht'),
  ('partnership.fit_eyebrow','fr','Conçu pour les spécialistes'),
  ('partnership.fit_eyebrow','es','Hecho para especialistas'),
  ('partnership.fit_title','en','The right work deserves the right context.'),
  ('partnership.fit_title','de','Die richtige Arbeit verdient den richtigen Kontext.'),
  ('partnership.fit_title','fr','Le bon travail mérite le bon contexte.'),
  ('partnership.fit_title','es','El trabajo adecuado merece el contexto adecuado.'),
  ('partnership.fit_intro','en','Whether you repair EVs, install charging equipment, protect finishes, or support the aftermarket, start with a profile that makes your scope clear to the people looking for it.'),
  ('partnership.fit_intro','de','Ob Sie EVs reparieren, Ladeausrüstung installieren, Oberflächen schützen oder den Aftermarket unterstützen: Beginnen Sie mit einem Profil, das Ihren Umfang für die richtigen Menschen klar macht.'),
  ('partnership.fit_intro','fr','Que vous répariez des VE, installiez des équipements de recharge, protégiez les finitions ou souteniez l''après-vente, commencez avec un profil qui rend votre expertise claire pour les personnes qui la recherchent.'),
  ('partnership.fit_intro','es','Ya sea que repares VE, instales equipos de carga, protejas acabados o apoyes la posventa, comienza con un perfil que aclare tu alcance a quienes lo buscan.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
