-- Community-first home copy in every supported locale.
insert into public.localized_content (content_key, locale, value) values
  ('home.eyebrow','en','The independent EV ownership network'),('home.eyebrow','de','Das unabhängige EV-Netzwerk für Eigentümer'),('home.eyebrow','fr','Le réseau indépendant des propriétaires de VE'),('home.eyebrow','es','La red independiente para propietarios de VE'),
  ('home.title','en','Get to the useful answer, {{accent}}.'),('home.title','de','Kommen Sie {{accent}} zur hilfreichen Antwort.'),('home.title','fr','Accédez {{accent}} à une réponse utile.'),('home.title','es','Llega a una respuesta útil, {{accent}}.'),
  ('home.title_accent','en','faster'),('home.title_accent','de','schneller'),('home.title_accent','fr','plus vite'),('home.title_accent','es','más rápido'),
  ('home.intro','en','Amped Up Network helps you move from a guided issue to community knowledge, expert context, and, only when hands-on service is needed, the right mechanic network.'),('home.intro','de','Amped Up Network führt Sie vom geführten Problem über Community-Wissen und Expertenkontext nur bei Bedarf zum passenden Werkstattnetzwerk.'),('home.intro','fr','Amped Up Network vous accompagne d''un problème guidé aux connaissances de la communauté, au contexte expert et, si nécessaire, au bon réseau de mécaniciens.'),('home.intro','es','Amped Up Network te lleva de un problema guiado al conocimiento de la comunidad, al contexto experto y, solo si hace falta servicio presencial, a la red de mecánicos adecuada.'),
  ('home.hero_cta','en','Solve a current problem'),('home.hero_cta','de','Ein aktuelles Problem lösen'),('home.hero_cta','fr','Résoudre un problème actuel'),('home.hero_cta','es','Resolver un problema actual'),
  ('home.hero_secondary','en','Browse the owner community'),('home.hero_secondary','de','Die Eigentümer-Community entdecken'),('home.hero_secondary','fr','Parcourir la communauté de propriétaires'),('home.hero_secondary','es','Explorar la comunidad de propietarios'),
  ('home.journey_eyebrow','en','One support chain'),('home.journey_eyebrow','de','Eine Unterstützungskette'),('home.journey_eyebrow','fr','Une chaîne d''accompagnement'),('home.journey_eyebrow','es','Una cadena de apoyo'),
  ('home.journey_title','en','Keep the useful context moving.'),('home.journey_title','de','Halten Sie hilfreichen Kontext in Bewegung.'),('home.journey_title','fr','Faites avancer le contexte utile.'),('home.journey_title','es','Mantén en marcha el contexto útil.'),
  ('home.journey_guided','en','Describe what your vehicle is telling you with guided issue context.'),('home.journey_guided','de','Beschreiben Sie mit geführtem Kontext, was Ihr Fahrzeug Ihnen mitteilt.'),('home.journey_guided','fr','Décrivez ce que votre véhicule vous indique avec un contexte guidé.'),('home.journey_guided','es','Describe lo que te indica tu vehículo con contexto guiado.'),
  ('home.journey_community','en','Learn from owners who have seen the same problem in the real world.'),('home.journey_community','de','Lernen Sie von Eigentümern mit Erfahrungen aus der Praxis.'),('home.journey_community','fr','Apprenez des propriétaires qui ont connu le même problème.'),('home.journey_community','es','Aprende de propietarios que han vivido el mismo problema.'),
  ('home.journey_expert','en','Bring in expert context when the answer needs more depth.'),('home.journey_expert','de','Holen Sie Expertenkontext ein, wenn die Antwort mehr Tiefe braucht.'),('home.journey_expert','fr','Ajoutez un contexte expert quand la réponse demande plus de profondeur.'),('home.journey_expert','es','Añade contexto experto cuando la respuesta necesite más profundidad.'),
  ('home.journey_service','en','Find a mechanic when hands-on service is the right next step.'),('home.journey_service','de','Finden Sie einen Fachbetrieb, wenn praktische Arbeit der nächste Schritt ist.'),('home.journey_service','fr','Trouvez un mécanicien quand un service pratique est la bonne suite.'),('home.journey_service','es','Encuentra un mecánico cuando el servicio presencial sea el siguiente paso.'),
  ('home.paths_eyebrow','en','Choose your next move'),('home.paths_eyebrow','de','Wählen Sie Ihren nächsten Schritt'),('home.paths_eyebrow','fr','Choisissez votre prochaine étape'),('home.paths_eyebrow','es','Elige tu siguiente paso'),
  ('home.paths_title','en','Support for the road you are on.'),('home.paths_title','de','Unterstützung für Ihren Weg.'),('home.paths_title','fr','Un accompagnement pour votre route.'),('home.paths_title','es','Apoyo para el camino en el que estás.'),
  ('home.path_issue','en','Solve a current problem'),('home.path_issue','de','Ein aktuelles Problem lösen'),('home.path_issue','fr','Résoudre un problème actuel'),('home.path_issue','es','Resolver un problema actual'),
  ('home.path_issue_intro','en','Capture the symptoms once and get to a useful next step.'),('home.path_issue_intro','de','Erfassen Sie Symptome einmal und finden Sie den nächsten hilfreichen Schritt.'),('home.path_issue_intro','fr','Décrivez les symptômes une fois et trouvez une suite utile.'),('home.path_issue_intro','es','Registra los síntomas una vez y llega a un siguiente paso útil.'),
  ('home.path_maintenance','en','Stay ahead of maintenance'),('home.path_maintenance','de','Wartung vorausdenken'),('home.path_maintenance','fr','Anticiper l''entretien'),('home.path_maintenance','es','Anticiparse al mantenimiento'),
  ('home.path_maintenance_intro','en','Use practical guides for safe checks and better shop visits.'),('home.path_maintenance_intro','de','Nutzen Sie praktische Anleitungen für sichere Prüfungen und bessere Werkstattbesuche.'),('home.path_maintenance_intro','fr','Utilisez des guides pratiques pour des vérifications sûres et de meilleures visites en atelier.'),('home.path_maintenance_intro','es','Usa guías prácticas para revisiones seguras y mejores visitas al taller.'),
  ('home.path_membership','en','Keep your support history'),('home.path_membership','de','Ihren Unterstützungsverlauf behalten'),('home.path_membership','fr','Conserver votre historique d''accompagnement'),('home.path_membership','es','Conservar tu historial de apoyo'),
  ('home.path_membership_intro','en','Save your issue context and unlock member support.'),('home.path_membership_intro','de','Speichern Sie Ihren Problemkontext und erhalten Sie Mitgliedersupport.'),('home.path_membership_intro','fr','Enregistrez le contexte de votre problème et accédez au soutien membre.'),('home.path_membership_intro','es','Guarda el contexto de tu problema y accede al apoyo de miembros.'),
  ('home.path_community','en','Compare notes with owners'),('home.path_community','de','Erfahrungen mit Eigentümern vergleichen'),('home.path_community','fr','Comparer les expériences avec des propriétaires'),('home.path_community','es','Comparar experiencias con propietarios'),
  ('home.path_community_intro','en','Browse real-world answers or ask the community.'),('home.path_community_intro','de','Entdecken Sie Antworten aus der Praxis oder fragen Sie die Community.'),('home.path_community_intro','fr','Parcourez des réponses réelles ou posez votre question à la communauté.'),('home.path_community_intro','es','Consulta respuestas reales o pregunta a la comunidad.'),
  ('home.path_catalog','en','Plan an upgrade'),('home.path_catalog','de','Ein Upgrade planen'),('home.path_catalog','fr','Préparer une amélioration'),('home.path_catalog','es','Planear una mejora'),
  ('home.path_catalog_intro','en','Order compatible services and upgrades.'),('home.path_catalog_intro','de','Bestellen Sie passende Services und Upgrades.'),('home.path_catalog_intro','fr','Commandez des services et améliorations compatibles.'),('home.path_catalog_intro','es','Pide servicios y mejoras compatibles.'),
  ('home.path_shops','en','Need hands-on service?'),('home.path_shops','de','Brauchen Sie praktische Hilfe?'),('home.path_shops','fr','Besoin d''un service pratique ?'),('home.path_shops','es','¿Necesitas servicio presencial?'),
  ('home.path_shops_intro','en','Search the independent mechanic network when it is time for a bay.'),('home.path_shops_intro','de','Durchsuchen Sie das unabhängige Werkstattnetzwerk, wenn es Zeit für eine Hebebühne ist.'),('home.path_shops_intro','fr','Recherchez le réseau de mécaniciens indépendants quand il est temps de passer à l''atelier.'),('home.path_shops_intro','es','Busca en la red de mecánicos independientes cuando sea hora de ir al taller.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
