-- Home pathway panels use the existing editable localized-content workflow.
insert into public.localized_content (content_key, locale, value) values
  ('home.intro', 'en', 'Keep the details of an EV issue together as you move from a question to the right kind of help.'),
  ('home.intro', 'de', 'Behalten Sie die Details eines EV-Problems zusammen, während Sie von einer Frage zur passenden Hilfe gelangen.'),
  ('home.intro', 'fr', 'Conservez les détails de votre problème de VE en passant d''une question à la bonne forme d''aide.'),
  ('home.intro', 'es', 'Mantén reunidos los detalles de un problema de tu VE mientras pasas de una pregunta a la ayuda adecuada.'),
  ('home.diagnose_eyebrow', 'en', 'The Volt Yard difference'),
  ('home.diagnose_eyebrow', 'de', 'Der Volt Yard Unterschied'),
  ('home.diagnose_eyebrow', 'fr', 'Ce que Volt Yard apporte'),
  ('home.diagnose_eyebrow', 'es', 'La diferencia de Volt Yard'),
  ('home.diagnose_title', 'en', 'Support that stays with the issue.'),
  ('home.diagnose_title', 'de', 'Support, der beim Problem bleibt.'),
  ('home.diagnose_title', 'fr', 'Un accompagnement qui suit le problème.'),
  ('home.diagnose_title', 'es', 'Apoyo que sigue el problema.'),
  ('home.diagnose_intro', 'en', 'Start with guided issue context, then keep one support loop from answers to experts to a service partner.'),
  ('home.diagnose_intro', 'de', 'Beginnen Sie mit einem geführten Problemkontext und bleiben Sie in einem Supportkreislauf von Antworten über Experten bis zum Servicepartner.'),
  ('home.diagnose_intro', 'fr', 'Commencez avec un contexte guidé, puis gardez une même boucle de soutien, des réponses aux experts jusqu''au partenaire de service.'),
  ('home.diagnose_intro', 'es', 'Empieza con un contexto guiado y mantén un mismo ciclo de apoyo, de las respuestas y expertos al socio de servicio.'),
  ('home.diagnose_answers', 'en', 'Guided context makes the next step clearer.'),
  ('home.diagnose_answers', 'de', 'Ein geführter Kontext macht den nächsten Schritt klarer.'),
  ('home.diagnose_answers', 'fr', 'Un contexte guidé clarifie la prochaine étape.'),
  ('home.diagnose_answers', 'es', 'El contexto guiado aclara el siguiente paso.'),
  ('home.diagnose_expertise', 'en', 'Answers, community, experts, and service stay connected.'),
  ('home.diagnose_expertise', 'de', 'Antworten, Community, Experten und Service bleiben verbunden.'),
  ('home.diagnose_expertise', 'fr', 'Réponses, communauté, experts et service restent connectés.'),
  ('home.diagnose_expertise', 'es', 'Respuestas, comunidad, expertos y servicio siguen conectados.'),
  ('home.diagnose_handoff', 'en', 'Members save issue history; Premium adds priority context and expert-response options.'),
  ('home.diagnose_handoff', 'de', 'Mitglieder speichern ihren Problemverlauf; Premium bietet priorisierten Kontext und Expertenantworten.'),
  ('home.diagnose_handoff', 'fr', 'Les membres conservent leur historique; Premium ajoute un contexte prioritaire et des réponses d''experts.'),
  ('home.diagnose_handoff', 'es', 'Los miembros guardan el historial; Premium añade contexto prioritario y opciones de respuesta experta.'),
  ('home.diagnose_cta', 'en', 'Try it out'),
  ('home.diagnose_cta', 'de', 'Jetzt ausprobieren'),
  ('home.diagnose_cta', 'fr', 'Essayer'),
  ('home.diagnose_cta', 'es', 'Pruébalo'),
  ('home.diagnose_membership', 'en', 'Explore Member and Premium support.'),
  ('home.diagnose_membership', 'de', 'Mitglieder- und Premium-Support entdecken.'),
  ('home.diagnose_membership', 'fr', 'Découvrir l''accompagnement Membre et Premium.'),
  ('home.diagnose_membership', 'es', 'Conoce el apoyo de Miembro y Premium.'),
  ('home.find_eyebrow', 'en', 'Just need a shop?'),
  ('home.find_eyebrow', 'de', 'Brauchen Sie nur eine Werkstatt?'),
  ('home.find_eyebrow', 'fr', 'Vous cherchez seulement un garage ?'),
  ('home.find_eyebrow', 'es', '¿Solo necesitas un taller?'),
  ('home.find_title', 'en', 'Find an EV service partner.'),
  ('home.find_title', 'de', 'Finden Sie einen EV-Servicepartner.'),
  ('home.find_title', 'fr', 'Trouvez un partenaire de service VE.'),
  ('home.find_title', 'es', 'Encuentra un socio de servicio para VE.'),
  ('home.find_intro', 'en', 'No pressure. Search independent shops and service partners near you when you already know what you need.'),
  ('home.find_intro', 'de', 'Ganz ohne Druck. Suchen Sie unabhängige Werkstätten und Servicepartner in Ihrer Nähe, wenn Sie bereits wissen, was Sie brauchen.'),
  ('home.find_intro', 'fr', 'Sans pression. Recherchez un garage indépendant ou un partenaire de service près de chez vous si vous savez déjà ce qu''il vous faut.'),
  ('home.find_intro', 'es', 'Sin presión. Busca talleres independientes y socios de servicio cerca de ti cuando ya sepas lo que necesitas.')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
