-- Expand the partnership page with marketing-oriented, non-promissory program copy.
insert into public.localized_content (content_key, locale, value) values
  ('partnership.levels_intro','en','Start where your business is ready. As evidence, outcomes, and participation grow, eligible partners can progress through the levels available for their class.'),
  ('partnership.levels_intro','de','Beginnen Sie dort, wo Ihr Unternehmen bereit ist. Mit wachsenden Nachweisen, Ergebnissen und Teilnahme können berechtigte Partner die für ihre Klasse verfügbaren Stufen durchlaufen.'),
  ('partnership.levels_intro','fr','Commencez là où votre entreprise est prête. À mesure que les preuves, résultats et la participation progressent, les partenaires admissibles peuvent évoluer à travers les niveaux disponibles pour leur catégorie.'),
  ('partnership.levels_intro','es','Comienza donde tu negocio esté listo. A medida que crecen la evidencia, los resultados y la participación, los socios elegibles pueden avanzar por los niveles disponibles para su clase.'),
  ('partnership.commercial_launch_intro','en','Your launch track is matched to your work. It may include profile development, scope and credential review, team training, customer-experience preparation, and class-appropriate launch support.'),
  ('partnership.commercial_launch_intro','de','Ihr Launch-Weg wird auf Ihre Arbeit abgestimmt. Er kann Profilentwicklung, Prüfung von Umfang und Nachweisen, Teamtraining, Vorbereitung der Kundenerfahrung und klassenbezogene Launch-Unterstützung umfassen.'),
  ('partnership.commercial_launch_intro','fr','Votre parcours de lancement est adapté à votre travail. Il peut inclure le développement du profil, l''examen du périmètre et des qualifications, la formation de l''équipe, la préparation de l''expérience client et un accompagnement de lancement adapté à votre catégorie.'),
  ('partnership.commercial_launch_intro','es','Tu ruta de lanzamiento se adapta a tu trabajo. Puede incluir desarrollo de perfil, revisión de alcance y credenciales, capacitación del equipo, preparación de experiencia del cliente y apoyo de lanzamiento apropiado para tu clase.'),
  ('partnership.commercial_ongoing_intro','en','Direct referrals keep the customer relationship and work with your shop: you quote, contract, bill, and warranty it. A fixed completed-booking fee may apply only to verified qualifying work, never a percentage of your sale.'),
  ('partnership.commercial_ongoing_intro','de','Direkte Empfehlungen belassen die Kundenbeziehung und Arbeit bei Ihrem Betrieb: Sie erstellen Angebote, schließen Verträge, stellen Rechnungen und gewährleisten die Arbeit. Eine feste Gebühr für abgeschlossene Buchungen kann nur für verifizierte qualifizierende Arbeit gelten, niemals als Prozentsatz Ihres Umsatzes.'),
  ('partnership.commercial_ongoing_intro','fr','Les recommandations directes maintiennent la relation client et le travail dans votre atelier : vous établissez le devis, le contrat, la facture et la garantie. Des frais fixes de réservation finalisée peuvent s''appliquer uniquement au travail qualifié vérifié, jamais sous forme de pourcentage de votre vente.'),
  ('partnership.commercial_ongoing_intro','es','Las referencias directas mantienen la relación con el cliente y el trabajo en tu taller: cotizas, contratas, facturas y garantizas el trabajo. Una tarifa fija por reserva completada puede aplicarse solo al trabajo calificado verificado, nunca como porcentaje de tu venta.'),
  ('partnership.case_eyebrow','en','More than a listing'),
  ('partnership.case_eyebrow','de','Mehr als ein Eintrag'),
  ('partnership.case_eyebrow','fr','Plus qu''une fiche'),
  ('partnership.case_eyebrow','es','Más que un listado'),
  ('partnership.case_title','en','Build a better way for EV owners to find your work.'),
  ('partnership.case_title','de','Schaffen Sie einen besseren Weg, damit EV-Eigentümer Ihre Arbeit finden.'),
  ('partnership.case_title','fr','Créez une meilleure façon pour les propriétaires de VE de trouver votre travail.'),
  ('partnership.case_title','es','Crea una mejor forma para que los propietarios de VE encuentren tu trabajo.'),
  ('partnership.case_intro','en','Amped Up Network connects EV-specific businesses with owners who need the right help. Your business remains independent: you set your pricing, perform your work, and stand behind it. We make the scope, context, and next step clearer for everyone involved.'),
  ('partnership.case_intro','de','Amped Up Network verbindet EV-spezifische Unternehmen mit Eigentümern, die die richtige Hilfe benötigen. Ihr Unternehmen bleibt unabhängig: Sie legen Ihre Preise fest, führen Ihre Arbeit aus und stehen dafür ein. Wir machen Umfang, Kontext und den nächsten Schritt für alle Beteiligten klarer.'),
  ('partnership.case_intro','fr','Amped Up Network met en relation des entreprises spécialisées dans les VE avec des propriétaires qui ont besoin de la bonne aide. Votre entreprise reste indépendante : vous fixez vos prix, réalisez votre travail et en assumez la responsabilité. Nous clarifions le périmètre, le contexte et la prochaine étape pour toutes les personnes impliquées.'),
  ('partnership.case_intro','es','Amped Up Network conecta empresas especializadas en VE con propietarios que necesitan la ayuda adecuada. Tu negocio sigue siendo independiente: estableces tus precios, realizas tu trabajo y lo respaldas. Hacemos más claros el alcance, el contexto y el siguiente paso para todos los involucrados.'),
  ('partnership.benefits_eyebrow','en','Built to help you grow'),
  ('partnership.benefits_eyebrow','de','Entwickelt, um Ihr Wachstum zu unterstützen'),
  ('partnership.benefits_eyebrow','fr','Conçu pour soutenir votre croissance'),
  ('partnership.benefits_eyebrow','es','Diseñado para ayudarte a crecer'),
  ('partnership.benefits_title','en','Marketing support, better context, and a trusted local presence.'),
  ('partnership.benefits_title','de','Marketingunterstützung, besserer Kontext und eine vertrauenswürdige lokale Präsenz.'),
  ('partnership.benefits_title','fr','Un soutien marketing, un meilleur contexte et une présence locale de confiance.'),
  ('partnership.benefits_title','es','Apoyo de marketing, mejor contexto y una presencia local confiable.'),
  ('partnership.benefit_context','en','Qualified context, not cold inquiries'),
  ('partnership.benefit_context','de','Qualifizierter Kontext statt kalter Anfragen'),
  ('partnership.benefit_context','fr','Un contexte qualifié, pas des demandes à froid'),
  ('partnership.benefit_context','es','Contexto calificado, no consultas en frío'),
  ('partnership.benefit_context_intro','en','Owners can carry their vehicle, issue, and service context forward with permission, so the right conversations start with less repeated intake.'),
  ('partnership.benefit_context_intro','de','Eigentümer können Fahrzeug-, Problem- und Servicekontext mit Erlaubnis weitergeben, sodass die richtigen Gespräche mit weniger wiederholter Aufnahme beginnen.'),
  ('partnership.benefit_context_intro','fr','Les propriétaires peuvent transmettre avec leur permission le contexte de leur véhicule, problème et service, afin que les bonnes conversations commencent avec moins de saisies répétées.'),
  ('partnership.benefit_context_intro','es','Los propietarios pueden trasladar el contexto de su vehículo, problema y servicio con permiso, para que las conversaciones adecuadas comiencen con menos información repetida.'),
  ('partnership.benefit_marketing','en','Launch marketing with substance'),
  ('partnership.benefit_marketing','de','Substanzvolles Launch-Marketing'),
  ('partnership.benefit_marketing','fr','Un marketing de lancement concret'),
  ('partnership.benefit_marketing','es','Marketing de lanzamiento con sustancia'),
  ('partnership.benefit_marketing_intro','en','Build a credible profile, a defined offer, and class-appropriate launch materials. Co-branded education, local events, and community activity are used where they make sense.'),
  ('partnership.benefit_marketing_intro','de','Erstellen Sie ein glaubwürdiges Profil, ein klar definiertes Angebot und klassenbezogene Launch-Materialien. Co-Branding-Bildung, lokale Veranstaltungen und Community-Aktivitäten werden eingesetzt, wo sie sinnvoll sind.'),
  ('partnership.benefit_marketing_intro','fr','Créez un profil crédible, une offre définie et des supports de lancement adaptés à votre catégorie. Des actions éducatives co-marquées, des événements locaux et des activités communautaires sont utilisés lorsqu''ils sont pertinents.'),
  ('partnership.benefit_marketing_intro','es','Crea un perfil creíble, una oferta definida y materiales de lanzamiento adecuados para tu clase. La educación conjunta, eventos locales y actividad comunitaria se utilizan cuando tienen sentido.'),
  ('partnership.benefit_reputation','en','Earn trust that compounds'),
  ('partnership.benefit_reputation','de','Vertrauen aufbauen, das wächst'),
  ('partnership.benefit_reputation','fr','Gagner une confiance qui s''accumule'),
  ('partnership.benefit_reputation','es','Gana confianza que se acumula'),
  ('partnership.benefit_reputation_intro','en','Show your actual scope, credentials, supported vehicles, and verified outcomes. Contribute useful expertise and build a reputation beyond a generic directory listing.'),
  ('partnership.benefit_reputation_intro','de','Zeigen Sie Ihren tatsächlichen Umfang, Ihre Nachweise, unterstützte Fahrzeuge und verifizierte Ergebnisse. Teilen Sie hilfreiche Expertise und bauen Sie einen Ruf auf, der über einen allgemeinen Verzeichniseintrag hinausgeht.'),
  ('partnership.benefit_reputation_intro','fr','Montrez votre véritable périmètre, vos qualifications, les véhicules pris en charge et les résultats vérifiés. Partagez une expertise utile et construisez une réputation au-delà d''une fiche d''annuaire générique.'),
  ('partnership.benefit_reputation_intro','es','Muestra tu alcance real, credenciales, vehículos compatibles y resultados verificados. Aporta experiencia útil y construye una reputación más allá de un listado genérico.'),
  ('partnership.close_eyebrow','en','Ready when you are'),
  ('partnership.close_eyebrow','de','Bereit, wenn Sie es sind'),
  ('partnership.close_eyebrow','fr','Prêt quand vous l''êtes'),
  ('partnership.close_eyebrow','es','Listo cuando tú lo estés'),
  ('partnership.close_title','en','Start the conversation about your place in the network.'),
  ('partnership.close_title','de','Beginnen Sie das Gespräch über Ihren Platz im Netzwerk.'),
  ('partnership.close_title','fr','Commencez la conversation sur votre place dans le réseau.'),
  ('partnership.close_title','es','Inicia la conversación sobre tu lugar en la red.'),
  ('partnership.close_intro','en','Tell us what you do, where you work, and the EV owners you serve. We will start with the right application and discuss the program path that fits your business.'),
  ('partnership.close_intro','de','Erzählen Sie uns, was Sie tun, wo Sie arbeiten und welche EV-Eigentümer Sie bedienen. Wir beginnen mit dem richtigen Antrag und besprechen den Programmweg, der zu Ihrem Unternehmen passt.'),
  ('partnership.close_intro','fr','Dites-nous ce que vous faites, où vous travaillez et les propriétaires de VE que vous servez. Nous commencerons par la bonne candidature et discuterons du parcours de programme adapté à votre entreprise.'),
  ('partnership.close_intro','es','Cuéntanos qué haces, dónde trabajas y a qué propietarios de VE atiendes. Comenzaremos con la solicitud adecuada y analizaremos la ruta de programa que se adapte a tu negocio.'),
  ('partnership.close_action','en','Start your partner application'),
  ('partnership.close_action','de','Partnerantrag starten'),
  ('partnership.close_action','fr','Commencer votre candidature partenaire'),
  ('partnership.close_action','es','Inicia tu solicitud de socio')
on conflict (content_key, locale) do update set value = excluded.value;

notify pgrst, 'reload schema';
